### ISSUE TITLE
option 'clones' should be a required field

### ISSUE THREAD

**Issue by 300481** [logstash-plugins/logstash-filter-clone#14]
If you use the clone plugin without defining the option 'clones',
the [code](https://github.com/logstash-plugins/logstash-filter-clone/blob/master/lib/logstash/filters/clone.rb#L25) will iterate over an empty array.
This is a no-op and makes no sense.

In my opinion the [documentation](https://www.elastic.co/guide/en/logstash/6.3/plugins-filters-clone.html#plugins-filters-clone-common-options) should be updated and mark the option 'clones' as required.

Additionally, the code should be extended and should throw an exception, if clones is not defined.
This should be an invalid configuration, because it would do nothing.

As it is currently, users could have a lot of time wasting with troubleshooting, searching the reason why their configs are not working as expected.

**Comment by jsvd** [comment]
to avoid breaking any sort of compatibility I created #15 that emits a warning that an empty 'clones' parameter will be a no-op.

**Comment by neu5ron** [comment]
+1,001

**Comment by neu5ron** [comment]
https://medium.com/@alhaynes/logstash-clone-filter-547421aabf6d
