### ISSUE TITLE
clone does not work

### ISSUE THREAD

**Issue by Skeeve** [logstash-plugins/logstash-filter-clone#17]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: "logstash.version"=>"6.4.0"
- Operating System: MacOS, Using Docker image of ELK Stack
- Config File:

```
    input {
        tcp {
            port => 5000
            codec => json
        }
     }
    filter {
        clone {
            add_tag => [ "scanner" ]
        }
    
     output {
        elasticsearch {
            hosts => "elasticsearch:9200"
            index => "testindex"
            document_type => "data"
        }
        stdout {}
    }
```

- Sample Data: 

    `echo '{"name":"DOMXSS","version":"1.5.0"}' | nc localhost 5000`

- Steps to Reproduce:

My stdout just shows one event without any tag:

    logstash_1       | {
    logstash_1       |        "version" => "1.5.0",
    logstash_1       |       "@version" => "1",
    logstash_1       |           "name" => "DOMXSS",
    logstash_1       |     "@timestamp" => 2019-02-07T08:19:35.302Z,
    logstash_1       |           "host" => "gateway",
    logstash_1       |           "port" => 33996
    logstash_1       | }

**Comment by Skeeve** [comment]
Ah! Seems I need to have something like this:

```
	clone {
		clones => ["data"]
		add_tag => [ "scanner" ]
	}
```

**Comment by jsvd** [comment]
version 4.0.0 makes clones parameter required. closing this.
