### ISSUE TITLE
this filter drops all @metadata

### ISSUE THREAD

**Issue by jpcarey** [logstash-plugins/logstash-filter-clone#5]

**Comment by wiibaa** [comment]
Confirmed! The issue is in the logstash event#clone method. I reported this in logstash-core and will look for a workaround.

**Comment by driverpt** [comment]
```
new_event = Logstash::Event.new(old_event.to_hash_with_metadata)
```

**Comment by jpcarey** [comment]
@wiibaa @driverpt simple change, thoughts? https://github.com/jpcarey/logstash-filter-clone/commit/ff4590169fc8c7969b160099690fb246f18007ab

**Comment by jordansissel** [comment]
I'm not sure if `to_hash_with_metadata` is a supported public API for the Event class.

**Comment by jordansissel** [comment]
We'll need an event duplication/clone method that copies the metadata for fixing this.

**Comment by wiibaa** [comment]
@jordansissel work on copying metadata + deep_clone is in progress in https://github.com/elastic/logstash/pull/4642

**Comment by uschtwill** [comment]
Why is this issue closed? As far as I can tell, metadata is still deleted when cloning?!

**Comment by wiibaa** [comment]
From the linked issues, it seems only fixed in the ruby implementation so LS 2.x and not in java event 5.x.
 @uschtwill thanks for reporting

**Comment by dmarkhas** [comment]
Hi,

Any ETA on when this will get fixed?

**Comment by alkuzad** [comment]
@dmarkhas go to upstream https://github.com/elastic/logstash/pull/4642 and ask @suyograo when it will be ported.

**Comment by dmarkhas** [comment]
FYI this was fixed in https://github.com/elastic/logstash/pull/8385
