### ISSUE TITLE
Enhance documentation about cloning and the semantics.

### ISSUE THREAD

**Issue by mjscosta** [logstash-plugins/logstash-filter-clone#7]
Clone semantics is not clear.

Please add to documentation, what is the clone behavior regarding where the cloned event is added to the pipeline. Whether the event, follows the workflow from the point where it is created via clone {}, or if it is reinserted into the beginning of pipeline.

**Comment by wiibaa** [comment]
@mjscosta Thanks for bringing this up. Would you have time to comment on this diagram if you think it would be useful to be added to the doc.

![yield-event-mechanism](https://jira-connect.gliffy.net/diagrams/e3e57640-0b64-11e6-a874-df7aba264bdd/preview?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2dzdGFzaC5qaXJhLmNvbSIsImlhdCI6MTQ2MTY0NTAyNSwiZXhwIjoxNDYxNjczODI1LCJxc2giOiJhOTNhYjQ1YzU0YjVhOTk2ZjNjNjJiMzI4NTJkNTliNjI0NWU4NGY2YmU3MzYwNTZlMmNmYjExMjNkNmFhZDQ1In0.UiDeJSCfvvDq4Ky2hR0EtLfaUbxtlUiwWcr7Xdedy90)

**Comment by mjscosta** [comment]
Hi @wiibaa , sure, I think its useful, though the diagram above is not very clear! Or some context is missing! 

In the documentation, maybe pipeline documentation, there should be some description about the relation of the configuration with the events flow.

As far as I understood, from code browsing, there is some "blackmagic" going on, in the cloning, and DSL generation and pipeline. In an abstract sense, I would split the DSL from the framework that manages the queue, and event filter stages ... Is you could enhance,a bit making a bridge, regarding the DSL, conditionals (if then else) and the stage the events are inserted, and provide some config samples exemplifying the semantics.

**Comment by zstyblik** [comment]
@wiibaa, please, can you publish that diagram again? Thank you.

**Comment by uschtwill** [comment]
@wiibaa, yes please: republish that diagram. That link is dead. Trial and error is the only way to find out right now, which is cumbersome.

**Comment by uschtwill** [comment]
Thanks @wiibaa! For future generations:

> Created events are inserted into the pipeline as normal events following the original event and will be processes by the remaining pipeline configuration starting form the filter that generated them.

**Comment by uschtwill** [comment]
@wiibaa: To clarify, when it says "starting from the filter that generated them" up there, it doesn't mean the filter block like `filter {...}` but the `clone {...}` filter plugin block itself, right? So in `filter { clone {...} ruby {...} }` the cloned events would still run through the ruby plugin, right?

I guess I just got confused by the word "filter" referring to both the plugins and the encapsulating block. Now that I think about it, individual filter plugins are quite commonly referred to as "filters"... right.

**Comment by zstyblik** [comment]
@uschtwill, I believe it means that cloned event(s) isn't inserted at the beginning of the pipeline, but exactly at the point where it was cloned. In other words, you must structure your pipeline accordingly.

**Comment by uschtwill** [comment]
Yes, indeed, that is how it is. I tried it out and it works like a charm. Documentation could still be enhanced - probably will do a PR the coming days.
